version: '3.8'
services:
  app:
    image: expense-tracking-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - expense-network

networks:
  expense-network:
    driver: bridge
